version: "3"
services:
  frontend:
    build: frontend
    ports:
      - "8080:8080"
    volumes:
      - ./frontend/:/app/
    environment:
      - CHOKIDAR_USEPOLLING=true

  backend:
    build: backend
    ports:
      - "3000:3000"
    volumes:
      - ./backend/:/app/
      - ./database_dumps:/dbdump
    depends_on:
      - database-1
    environment:
      - CHOKIDAR_USEPOLLING=true

  database-1:
    image: mysql:5.7.28
    ports:
      - "3306:3306"
    volumes:
      - ./database-src/:/var/lib/mysql
      - ./database_dumps/:/dbdump
      - ./scripts:/docker-entrypoint-initdb.d/
    environment:
      - MYSQL_ROOT_PASSWORD=${SRCDBPASS}
      - MYSQL_DATABASE=${SRCDB}

  database-2:
    image: postgres:9.6.16
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data/
    environment:
      # - POSTGRES_USER=root
      - POSTGRES_PASSWORD=${DESTDBPASS}
      - POSTGRES_DB=${DESTDB}
      - PGDATA=/var/lib/postgresql/data/pgdata

  database-3:
    image: mysql:5.7.28
    ports:
      - "3307:3306"
    volumes:
      - ./database-dest/:/var/lib/mysql
      - ./database_dumps/:/dbdump
    #  - ./scripts:/docker-entrypoint-initdb.d/
    environment:
      - MYSQL_ROOT_PASSWORD=${SRCDBPASS}
      - MYSQL_DATABASE=${SRCDB}

  adminer:
    image: adminer
    ports: 
      - "8081:8080"

volumes: 
  pgdata:
    driver: local